"""
signals/mock_kb.py
------------------
Phase 7: Placeholder knowledge base — 25 entries.

ALL content is mock/placeholder.
Real entries can be loaded from markdown/JSON files without changing
the retriever interface (kb_retriever.py).

Each entry shape:
{
    title:            str,
    domain:           str,
    source:           str,
    type:             "textbook" | "research" | "curriculum" | "news",
    confidence_base:  float,   # baseline confidence before query matching
    content:          str,
    keywords:         list[str],
}
"""
from __future__ import annotations

from typing import Any, Dict, List

MOCK_KB: List[Dict[str, Any]] = [
    {
        "title": "Qubit Fundamentals",
        "domain": "quantum",
        "source": "Placeholder Quantum Textbook v1",
        "type": "textbook",
        "confidence_base": 0.92,
        "content": "[PLACEHOLDER] A qubit is a two-level quantum system. It can exist in superposition of |0⟩ and |1⟩ states simultaneously.",
        "keywords": ["qubit", "quantum", "two-level", "superposition"],
    },
    {
        "title": "Quantum Entanglement Overview",
        "domain": "quantum",
        "source": "Placeholder Quantum Textbook v1",
        "type": "textbook",
        "confidence_base": 0.90,
        "content": "[PLACEHOLDER] Entanglement is a quantum phenomenon where two particles share a correlated quantum state regardless of distance.",
        "keywords": ["entanglement", "quantum", "correlated", "particles"],
    },
    {
        "title": "Grover's Search Algorithm",
        "domain": "quantum",
        "source": "Placeholder Research Paper — Grover 1996",
        "type": "research",
        "confidence_base": 0.88,
        "content": "[PLACEHOLDER] Grover's algorithm provides a quadratic speedup for unstructured database search using quantum amplitude amplification.",
        "keywords": ["grover", "algorithm", "search", "quantum", "speedup"],
    },
    {
        "title": "Shor's Factoring Algorithm",
        "domain": "quantum",
        "source": "Placeholder Research Paper — Shor 1994",
        "type": "research",
        "confidence_base": 0.89,
        "content": "[PLACEHOLDER] Shor's algorithm factors large integers in polynomial time using quantum Fourier transform, threatening RSA encryption.",
        "keywords": ["shor", "algorithm", "factoring", "quantum", "rsa"],
    },
    {
        "title": "Quantum Superposition Principle",
        "domain": "quantum",
        "source": "Placeholder Quantum Textbook v1",
        "type": "textbook",
        "confidence_base": 0.87,
        "content": "[PLACEHOLDER] Superposition allows a quantum system to be in multiple states simultaneously until measured.",
        "keywords": ["superposition", "quantum", "measurement", "states"],
    },
    {
        "title": "Mahavira — Life and Teachings",
        "domain": "jain",
        "source": "Placeholder Jain Studies Reference",
        "type": "curriculum",
        "confidence_base": 0.91,
        "content": "[PLACEHOLDER] Vardhamana Mahavira (599–527 BCE) is the 24th Tirthankara of Jainism. He taught ahimsa, satya, and aparigraha.",
        "keywords": ["mahavira", "jain", "tirthankara", "ahimsa"],
    },
    {
        "title": "Ahimsa in Jain Ethics",
        "domain": "jain",
        "source": "Placeholder Jain Ethics Curriculum",
        "type": "curriculum",
        "confidence_base": 0.90,
        "content": "[PLACEHOLDER] Ahimsa (non-violence) is the supreme principle of Jainism, applied to thought, speech, and action.",
        "keywords": ["ahimsa", "jain", "non-violence", "ethics"],
    },
    {
        "title": "Jain Karma Doctrine",
        "domain": "jain",
        "source": "Placeholder Jain Philosophy Text",
        "type": "textbook",
        "confidence_base": 0.85,
        "content": "[PLACEHOLDER] Jain karma theory holds that karma is a subtle matter that binds to the soul through actions, thoughts, and speech.",
        "keywords": ["karma", "jain", "soul", "doctrine"],
    },
    {
        "title": "Vachanamrut Core Teachings",
        "domain": "swaminarayan",
        "source": "Placeholder Swaminarayan Scripture Reference",
        "type": "curriculum",
        "confidence_base": 0.91,
        "content": "[PLACEHOLDER] The Vachanamrut is the primary scripture of the Swaminarayan Sampradaya, containing 273 discourses on theology and ethics.",
        "keywords": ["vachanamrut", "swaminarayan", "scripture", "discourses"],
    },
    {
        "title": "Swamini Vato",
        "domain": "swaminarayan",
        "source": "Placeholder Swaminarayan Secondary Scripture",
        "type": "curriculum",
        "confidence_base": 0.88,
        "content": "[PLACEHOLDER] Swamini Vato records the spiritual teachings of Gunatitanand Swami, the first successor of Swaminarayan.",
        "keywords": ["swamini vato", "swaminarayan", "gunatitanand", "teachings"],
    },
    {
        "title": "Nyaya Logic System",
        "domain": "gurukul",
        "source": "Placeholder Indian Philosophy Curriculum",
        "type": "curriculum",
        "confidence_base": 0.86,
        "content": "[PLACEHOLDER] Nyaya is the school of Indian logic defining four valid sources of knowledge: perception, inference, comparison, and testimony.",
        "keywords": ["nyaya", "logic", "indian", "philosophy", "pramana"],
    },
    {
        "title": "Vedic Mathematics Principles",
        "domain": "gurukul",
        "source": "Placeholder Vedic Math Curriculum",
        "type": "curriculum",
        "confidence_base": 0.84,
        "content": "[PLACEHOLDER] Vedic mathematics uses 16 sutras for rapid mental calculation, including Ekadhikena Purvena and Nikhilam.",
        "keywords": ["vedic", "math", "mathematics", "sutras", "calculation"],
    },
    {
        "title": "University Admission Process",
        "domain": "admissions",
        "source": "Placeholder Admissions Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.87,
        "content": "[PLACEHOLDER] University admissions involve entrance exams, merit list publication, counseling rounds, document verification, and fee payment.",
        "keywords": ["admission", "university", "counseling", "merit", "process"],
    },
    {
        "title": "Counseling Round Explained",
        "domain": "admissions",
        "source": "Placeholder Admissions Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.85,
        "content": "[PLACEHOLDER] A counseling round allows eligible students to select seats based on merit rank. Documents and payment must be ready within the acceptance window.",
        "keywords": ["counseling", "round", "seat", "admission", "merit"],
    },
    {
        "title": "Admission Eligibility Criteria",
        "domain": "admissions",
        "source": "Placeholder Admissions Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.86,
        "content": "[PLACEHOLDER] Eligibility for admission typically requires minimum percentage marks, valid entrance exam score, and category certificate if applicable.",
        "keywords": ["eligibility", "admission", "marks", "entrance", "criteria"],
    },
    {
        "title": "Resume Preparation for Placements",
        "domain": "placement",
        "source": "Placeholder Career Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.88,
        "content": "[PLACEHOLDER] A placement resume should highlight measurable achievements, relevant projects, and skills aligned to the target role. Avoid vague statements.",
        "keywords": ["resume", "placement", "career", "achievements", "skills"],
    },
    {
        "title": "Placement Interview Preparation",
        "domain": "placement",
        "source": "Placeholder Career Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.87,
        "content": "[PLACEHOLDER] Interview preparation includes technical rounds, HR rounds, aptitude tests, and group discussions. Practice with mock interviews.",
        "keywords": ["interview", "placement", "preparation", "technical", "hr"],
    },
    {
        "title": "LinkedIn Profile Optimisation",
        "domain": "placement",
        "source": "Placeholder Career Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.82,
        "content": "[PLACEHOLDER] A strong LinkedIn profile includes a professional headline, summary, skills section, and endorsements from peers and mentors.",
        "keywords": ["linkedin", "profile", "career", "placement", "optimisation"],
    },
    {
        "title": "Referral Request Strategy",
        "domain": "placement",
        "source": "Placeholder Career Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.80,
        "content": "[PLACEHOLDER] Requesting a referral requires a personalised message, clear role specification, and a concise summary of your fit for the position.",
        "keywords": ["referral", "career", "placement", "request", "strategy"],
    },
    {
        "title": "Quantum Biology Overview",
        "domain": "quantum",
        "source": "Placeholder Quantum Biology Research",
        "type": "research",
        "confidence_base": 0.83,
        "content": "[PLACEHOLDER] Quantum biology studies quantum effects in biological systems such as photosynthesis, enzyme catalysis, and bird navigation.",
        "keywords": ["quantum", "biology", "photosynthesis", "enzyme", "navigation"],
    },
    {
        "title": "Quantum Hardware Platforms",
        "domain": "quantum",
        "source": "Placeholder Quantum Hardware Survey",
        "type": "research",
        "confidence_base": 0.81,
        "content": "[PLACEHOLDER] Quantum hardware platforms include superconducting qubits, trapped ions, photonic systems, and topological qubits.",
        "keywords": ["quantum", "hardware", "superconducting", "trapped ions", "photonic"],
    },
    {
        "title": "Density Matrix Formalism",
        "domain": "quantum",
        "source": "Placeholder Quantum Textbook v1",
        "type": "textbook",
        "confidence_base": 0.85,
        "content": "[PLACEHOLDER] The density matrix ρ describes mixed quantum states. For a pure state |ψ⟩, ρ = |ψ⟩⟨ψ|. Trace of ρ equals 1.",
        "keywords": ["density", "matrix", "quantum", "mixed", "state"],
    },
    {
        "title": "Reporting Day Checklist",
        "domain": "admissions",
        "source": "Placeholder Admissions Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.84,
        "content": "[PLACEHOLDER] On reporting day bring: allotment letter, mark sheets, ID proof, category certificate, passport photos, and fee payment receipt.",
        "keywords": ["reporting", "day", "checklist", "admission", "documents"],
    },
    {
        "title": "GitHub Portfolio Cleanup",
        "domain": "placement",
        "source": "Placeholder Career Support Dataset",
        "type": "curriculum",
        "confidence_base": 0.79,
        "content": "[PLACEHOLDER] A clean GitHub portfolio pins top repositories, adds README files with project descriptions, and removes incomplete or test projects.",
        "keywords": ["github", "portfolio", "placement", "cleanup", "repositories"],
    },
    {
        "title": "Quantum Software Stack",
        "domain": "quantum",
        "source": "Placeholder Quantum Software Survey",
        "type": "research",
        "confidence_base": 0.82,
        "content": "[PLACEHOLDER] The quantum software stack includes circuit compilers, simulators, cloud access layers, and high-level quantum programming frameworks.",
        "keywords": ["quantum", "software", "stack", "compiler", "simulator"],
    },
]
